DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS blogs;
CREATE TABLE users (
  userid INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  hash_passwd TEXT NOT NULL,
  displayname TEXT NOT NULL
);
CREATE TABLE blogs (
  blog_id INTEGER PRIMARY KEY AUTOINCREMENT,
  userid INTEGER NOT NULL,
  auther TEXT NOT NULL,
  title TEXT NOT NULL,
  FOREIGN KEY (userid) REFERENCES users (userid)
);