DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS blogs;
CREATE TABLE users (
  userid INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  hashpassword TEXT NOT NULL,
  displayname TEXT NOT NULL
);
CREATE TABLE blogs (
  blogid INTEGER PRIMARY KEY AUTOINCREMENT,
  userid INTEGER NOT NULL,
  title TEXT NOT NULL,
  auther TEXT NOT NULL,
  content TEXT NOT NULL,
  last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userid) REFERENCES users (userid)
);